title: Jason Lopez 
description: This portfolio includes the work that I have done during my time at university and laboratory internship(s). 
theme: just-the-docs

url: https://jasonkylopez.github.io/workportfolio

aux_links:
  LinkedIn: https://www.linkedin.com/in/jasonkylopez/
